server:
  port: 10000


spring:
  devtools:
    restart:
      exclude: "**/dto/**"

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      timeout: 60000

  cache:
    type: redis

  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/XE
      username: hr
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "24821996907-94rqj1ogp5vcm49qkshephjrsd2b25i2.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:10000/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google
          naver:
            client-id: "M1NYqH07xh0uqc18SJPL"
            client-secret: "NJ3QjDnu8j"
            scope:
              - name
              - email
            redirect-uri: "http://localhost:10000/login/oauth2/code/naver"  # 네이버 콜백 URL
            authorization-grant-type: authorization_code
            client-name: Naver
            provider: naver
          kakao:
            client-id: "26fb78b6feb1da14eb7c0fa10b20bb83"
            scope:
              - profile_nickname
              - account_email
              - profile_image
            redirect-uri: "http://localhost:10000/login/oauth2/code/kakao"  # 카카오 콜백 URL
            authorization-grant-type: authorization_code
            client-name: Kakao
            provider: kakao
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: name
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



jwt:
  secret: "myverylongsecretkeythatis256bitlong1234567890abcdefgh"
  token-blacklist-prefix: "blacklist:"
  refresh-blacklist-prefix: "refresh:"

